on:
  push:
    branches:
      - main

name: Tag for Release
jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: release-please-action
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false}]'

      - name: debug
        run: |
          echo "${{ steps.release }}"
          echo "${{ steps.release.outputs }}"
          echo "${{ steps.release.outputs.release_created }}"
          echo "${{ steps.release.outputs.sha }}"
          echo "${{ steps.release.outputs.major }}"
          echo ${{ steps.release.outputs.minor }}
          echo ${{ steps.release.outputs.patch }}
  second-job:
    needs: release-please
    if: needs.release-please.outputs.release_created
    runs-on: ubuntu-latest
    steps:
      - name: debug2
        run: |
          echo "second job"
          echo ${{ needs.release-please.outputs.release_created }}
  third-job:
    runs-on: ubuntu-latest
    steps:
      - name: debug3
        run: |
          echo "third job"


    