on:
  push:
    branches:
      - main

name: Tag for Release
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v1.3.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          package-name: release-please-action
      - name: debug
        run: |
          echo ${{ steps.release.outputs.release_created }}
          echo ${{ steps.release.outputs.sha }}
          echo ${{ steps.release.outputs.major }}
          echo ${{ steps.release.outputs.minor }}
          echo ${{ steps.release.outputs.patch }}
    